#!/usr/bin/env python3

from pathlib import Path

import numpy as np
from scipy.signal import firwin, freqz

FS_IN = 64000
FS_OUT = 8192

UP = 16
DOWN = 125

FS_UP = FS_IN * UP

PASSBAND_HZ = 2000
STOPBAND_HZ = 4096

NUM_TAPS = 2464
KAISER_BETA = 7.857260
CUTOFF_HZ = (PASSBAND_HZ + STOPBAND_HZ) / 2.0

MAX_PASSBAND_RIPPLE_DB = 0.01
MAX_STOPBAND_DB = -80.0
COEFFICIENT_SUM_TOLERANCE = 1e-6

OUTPUT_FILE = (
    Path(__file__).resolve().parents[2]
    / "core/include/dsp/resampler_16_125_taps.h"
)


def main():

    if NUM_TAPS % UP != 0:
        raise RuntimeError(
            f"NUM_TAPS ({NUM_TAPS}) must be divisible by UP ({UP})"
        )

    if FS_IN * UP % DOWN != 0:
        raise RuntimeError("Resampling ratio does not produce integer output Fs")

    calculated_fs_out = FS_IN * UP // DOWN

    if calculated_fs_out != FS_OUT:
        raise RuntimeError(
            f"Output Fs mismatch: {calculated_fs_out} != {FS_OUT}"
        )

    if STOPBAND_HZ > FS_OUT / 2:
        raise RuntimeError("Stopband start exceeds output Nyquist frequency")

    taps = firwin(
        NUM_TAPS,
        CUTOFF_HZ,
        window=("kaiser", KAISER_BETA),
        fs=FS_UP
    )

    w, h = freqz(
        taps,
        worN=1048576,
        fs=FS_UP
    )

    magnitude = np.abs(h)

    passband = magnitude[w <= PASSBAND_HZ]
    stopband = magnitude[w >= STOPBAND_HZ]

    passband_db = 20.0 * np.log10(
        np.maximum(passband, 1e-300)
    )

    stopband_db = 20.0 * np.log10(
        np.maximum(stopband, 1e-300)
    )

    passband_ripple_db = (
        np.max(passband_db) -
        np.min(passband_db)
    )

    stopband_max_db = np.max(stopband_db)
    coefficient_sum = np.sum(taps)

    print("Pi5-HRO 64k -> 8192 rational resampler")
    print(f"Input sample rate : {FS_IN} Hz")
    print(f"Interpolation     : {UP}")
    print(f"Decimation        : {DOWN}")
    print(f"Output sample rate: {FS_OUT} Hz")
    print(f"Design sample rate: {FS_UP} Hz")
    print(f"Passband edge     : {PASSBAND_HZ} Hz")
    print(f"Stopband start    : {STOPBAND_HZ} Hz")
    print(f"Cutoff            : {CUTOFF_HZ} Hz")
    print(f"Taps              : {NUM_TAPS}")
    print(f"Taps / phase      : {NUM_TAPS // UP}")
    print(f"Kaiser beta       : {KAISER_BETA}")
    print(f"Passband ripple   : {passband_ripple_db:.6f} dB")
    print(f"Stopband max      : {stopband_max_db:.6f} dB")
    print(f"Coefficient sum   : {coefficient_sum:.12f}")

    if passband_ripple_db > MAX_PASSBAND_RIPPLE_DB:
        raise RuntimeError("Passband ripple requirement FAILED")

    if stopband_max_db > MAX_STOPBAND_DB:
        raise RuntimeError("Stopband attenuation requirement FAILED")

    if abs(coefficient_sum - 1.0) > COEFFICIENT_SUM_TOLERANCE:
        raise RuntimeError("Coefficient sum requirement FAILED")

    print("Design validation: PASS")

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)

    with OUTPUT_FILE.open("w", encoding="utf-8") as f:

        f.write("// AUTO-GENERATED FILE - DO NOT EDIT\n")
        f.write("// Generated by tools/dsp/design_resampler_64k_to_8192.py\n")
        f.write("#pragma once\n\n")
        f.write("#include <array>\n\n")
        f.write("namespace hro::dsp {\n\n")

        f.write(
            f"inline constexpr std::array<float, {NUM_TAPS}> "
            "kResampler16_125Taps = {\n"
        )

        for i, value in enumerate(taps):
            f.write(f"    {value:.12e}f")

            if i != NUM_TAPS - 1:
                f.write(",")

            f.write("\n")

        f.write("};\n\n")
        f.write("} // namespace hro::dsp\n")

    print(f"Generated: {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
    